pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'CI/CD-testing', url: 'https://github.com/Rorschach-IT/People-16-personalities.git'
            }
        }

        stage('Restore & Build .NET') {
            steps {
			    dir('src/PeoplePersonalities/PeoplePersonalities') {
					bat 'dotnet clean'
					bat 'dotnet build'
				}
            }
        }
		
		stage('Run application') {
			steps {
				bat 'start "" dotnet run --urls http://0.0.0.0:5188'
				// mały sleep, żeby serwer wstał
				bat 'ping 127.0.0.1 -n 10 >nul'
			}
		}

        stage('Install Cypress deps') {
            steps {
                dir('tests/cypress') {
                    bat 'npm ci'
                }
            }
        }

        stage('Run Cypress tests') {
            steps {
				bat 'npm run test:all'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'tests/cypress/cypress/videos/**/*.*, tests/cypress/cypress/screenshots/**/*.*', allowEmptyArchive: true
        }
    }
}