pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'CI/CD-testing', url: 'https://github.com/Rorschach-IT/People-16-personalities.git'
            }
        }

        stage('Restore & Build .NET') {
            steps {
			    dir('src/PeoplePersonalities/PeoplePersonalities')
                bat 'dotnet clean'
                bat 'dotnet build'
				bat 'dotnet run'
            }
        }

        stage('Install Cypress deps') {
            steps {
                dir('tests/cypress') {
                    bat 'npm ci'
                }
            }
        }

        stage('Run Cypress tests') {
            steps {
                dir('tests/cypress') {
                    bat 'npm run test:all'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'tests/cypress/cypress/videos/**/*.*, tests/cypress/cypress/screenshots/**/*.*', allowEmptyArchive: true
        }
    }
}